"""R1: what does one real event cost on Redis Streams, in each candidate encoding?

Answers exactly the question #58 asks and nothing else: the byte size of one real
`md.option_quote` and one `md.option_reference` — and, because the derivation needs it,
one `md.index_quote` — under the candidate encodings, then the memory that implies at
thirty minutes' retention.

Run from `engine/`:

    .venv/Scripts/python.exe ../tools/measure_payload_size.py

A Redis on `127.0.0.1:6399` turns the last two tables on. Without one the byte counts
still print and the Redis-measured columns say so. Every number printed is `measured` on
this machine, this run, off the committed fixtures in `engine/tests/fixtures/`.

**The five encodings.** Each is a *whole Redis stream entry* — `XADD key * f v [f v ...]`
— because that, not the payload alone, is what Redis stores and what a reader parses.

  A `json:one-field`        one field, `payload`, the whole event as JSON.
  B `json:envelope-flat`    the envelope's seven fields flat, one Redis field each, and
                            `payload` holding the type-specific keys as JSON. #57's
                            working proposal.
  C `msgpack:envelope-flat` the same flat envelope, `payload` as MessagePack.
  D `msgpack:one-field`     one field, the whole event as MessagePack.
  E `protobuf:one-field`    `type` plus `payload` as protobuf, the shape Nautilus Trader
                            writes (`topic`/`type`/`payload`/`encoding` fields).

**The protobuf encoder here is hand-written against the wire format** rather than
generated by `protoc`, which is not installed. `_verify_protobuf_encoder` checks it
against the `google.protobuf` runtime on a fully-populated message before any size is
reported, so the numbers are the real wire format and not this file's opinion of it.
Nullable fields are omitted entirely when absent, which is proto3 explicit presence.
"""

from __future__ import annotations

import json
import struct
import sys
from collections import OrderedDict
from datetime import datetime
from decimal import Decimal
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "engine" / "src"))

import msgpack  # noqa: E402

from deltapayoff.adapters import DeltaAdapter  # noqa: E402
from deltapayoff.adapters.delta_socket import BOOK_CHANNEL, TICKER_CHANNEL  # noqa: E402
from deltapayoff.events import (  # noqa: E402
    Event,
    IndexQuote,
    OptionQuote,
    OptionReference,
)

FIXTURES = ROOT / "engine" / "tests" / "fixtures"
REDIS_URL = "redis://127.0.0.1:6399"

#: The seven envelope fields. Everything else on an event is its payload.
ENVELOPE = (
    "type",
    "event_id",
    "schema_version",
    "source",
    "ts_venue",
    "ts_received",
    "instrument",
)

#: `measured`, `tools/measure_feed.py`, 2026-09-08: 1,693.6 venue frames a second over
#: BTC+ETH, 782 contracts. Split into the two channels by their `measured` per-contract
#: refresh intervals, 508 ms on the book and 5,001 ms on the ticker (2026-09-03).
FRAMES_PER_SECOND = 1693.6
BOOK_INTERVAL_S = 0.508
TICKER_INTERVAL_S = 5.001
RETENTION_SECONDS = 30 * 60


# ------------------------------------------------------------------ real events


def _decode(fixture: str, channel: str) -> list[Event]:
    """Every event the real adapter decode produces from a captured fixture."""
    adapter = DeltaAdapter(client=object(), feed_factory=lambda sink, **kw: object())
    frames = json.loads((FIXTURES / fixture).read_text())["frames"]
    frames = list(frames.values()) if isinstance(frames, dict) else list(frames)
    events: list[Event] = []
    for frame in frames:
        events.extend(
            adapter.events_from_frame(channel, frame, received_at=1788431316.0)
        )
    return events


def real_events() -> dict[str, list[Event]]:
    book = _decode("ws-ob-l2-04-09-2026.json", BOOK_CHANNEL)
    ticker = _decode("ws-ticker-04-09-2026.json", TICKER_CHANNEL)
    return {
        "md.option_quote": [e for e in book if isinstance(e, OptionQuote)],
        "md.option_reference": [e for e in ticker if isinstance(e, OptionReference)],
        "md.index_quote": [e for e in ticker if isinstance(e, IndexQuote)],
    }


# ------------------------------------------------------------------ encodings


def _payload_json(event: Event) -> dict[str, Any]:
    """The type-specific keys, JSON-shaped. `null` stays `null`."""
    dumped = event.model_dump(mode="json")
    return {k: v for k, v in dumped.items() if k not in ENVELOPE}


def _payload_native(event: Event) -> dict[str, Any]:
    """The same keys, binary-shaped: datetimes as UNIX microseconds, decimals as floats.

    Nautilus Trader's default is the same choice — `timestamps_as_iso8601: false`, and
    "timestamps will be persisted as UNIX nanoseconds".
    """
    out: dict[str, Any] = {}
    for key, value in event.model_dump(mode="python").items():
        if key in ENVELOPE:
            continue
        if isinstance(value, datetime):
            value = int(value.timestamp() * 1e6)
        elif isinstance(value, Decimal):
            value = float(value)
        out[key] = value
    return out


def _envelope_flat(event: Event) -> dict[str, bytes]:
    """The envelope, one Redis field per key. Absent keys are omitted, never spelled."""
    fields: dict[str, bytes] = {
        "type": event.type.encode(),
        "event_id": event.event_id.encode(),
        "schema_version": str(event.schema_version).encode(),
        "source": event.source.encode(),
        "ts_received": event.ts_received.isoformat().encode(),
    }
    if event.ts_venue is not None:
        fields["ts_venue"] = event.ts_venue.isoformat().encode()
    if event.instrument is not None:
        fields["instrument"] = event.instrument.canonical().encode()
        if event.instrument.venue_symbol:
            fields["venue_symbol"] = event.instrument.venue_symbol.encode()
    return fields


def encode_json_one_field(event: Event) -> dict[str, bytes]:
    return {"payload": event.model_dump_json().encode()}


def encode_json_envelope_flat(event: Event) -> dict[str, bytes]:
    fields = _envelope_flat(event)
    fields["payload"] = json.dumps(_payload_json(event), separators=(",", ":")).encode()
    return fields


def encode_msgpack_envelope_flat(event: Event) -> dict[str, bytes]:
    fields = _envelope_flat(event)
    fields["payload"] = msgpack.packb(_payload_native(event), use_bin_type=True)
    return fields


def encode_msgpack_one_field(event: Event) -> dict[str, bytes]:
    whole = dict(_payload_native(event))
    whole.update(
        {
            "type": event.type,
            "event_id": event.event_id,
            "schema_version": event.schema_version,
            "source": event.source,
            "ts_venue": None
            if event.ts_venue is None
            else int(event.ts_venue.timestamp() * 1e6),
            "ts_received": int(event.ts_received.timestamp() * 1e6),
            "instrument": None
            if event.instrument is None
            else event.instrument.canonical(),
        }
    )
    return {"payload": msgpack.packb(whole, use_bin_type=True)}


# ------------------------------------------------------------------ protobuf


def _varint(value: int) -> bytes:
    out = bytearray()
    while True:
        byte = value & 0x7F
        value >>= 7
        if value:
            out.append(byte | 0x80)
        else:
            out.append(byte)
            return bytes(out)


def _tag(field: int, wire: int) -> bytes:
    return _varint((field << 3) | wire)


def _pb_string(field: int, value: str | None) -> bytes:
    if value is None:
        return b""
    raw = value.encode()
    return _tag(field, 2) + _varint(len(raw)) + raw


def _pb_double(field: int, value: float | None) -> bytes:
    if value is None:
        return b""
    return _tag(field, 1) + struct.pack("<d", value)


def _pb_int(field: int, value: int | None) -> bytes:
    if value is None:
        return b""
    return _tag(field, 0) + _varint(value)


def _pb_message(field: int, body: bytes) -> bytes:
    return _tag(field, 2) + _varint(len(body)) + body


def _pb_instrument(event: Event) -> bytes:
    inst = event.instrument
    if inst is None:
        return b""
    body = (
        _pb_string(1, inst.venue)
        + _pb_string(2, inst.underlying)
        + _pb_int(3, int(inst.expiry.strftime("%Y%m%d")))
        + _pb_double(4, float(inst.strike))
        + _pb_int(5, 1 if inst.right.value == "C" else 2)
        + _pb_string(6, inst.venue_symbol)
    )
    return _pb_message(6, body)


def _micros(stamp: datetime | None) -> int | None:
    return None if stamp is None else int(stamp.timestamp() * 1e6)


def _pb_envelope(event: Event) -> bytes:
    """Fields 1-6, identical across all nine messages. `type` is the message type and so
    rides in the Redis `type` field, not in the payload — Nautilus does the same."""
    return (
        _pb_string(1, event.event_id)
        + _pb_int(2, event.schema_version)
        + _pb_string(3, event.source)
        + _pb_int(4, _micros(event.ts_venue))
        + _pb_int(5, _micros(event.ts_received))
        + _pb_instrument(event)
    )


#: Payload field numbers, per event type. 1-15 cost a one-byte tag, 16+ two.
_PB_PAYLOAD: dict[str, tuple[tuple[int, str, str], ...]] = {
    "md.option_quote": (
        (7, "bid", "d"),
        (8, "bid_size", "d"),
        (9, "ask", "d"),
        (10, "ask_size", "d"),
        (11, "lts", "t"),
    ),
    "md.option_reference": (
        (7, "product_id", "i"),
        (8, "mark", "d"),
        (9, "last_price", "d"),
        (10, "turnover", "d"),
        (11, "bid", "d"),
        (12, "ask", "d"),
        (13, "oi", "d"),
        (14, "oi_value_usd", "d"),
        (15, "oi_change_usd_6h", "d"),
        (16, "tick_size", "d"),
        (17, "bid_iv", "d"),
        (18, "ask_iv", "d"),
        (19, "mark_iv", "d"),
        (20, "delta", "d"),
        (21, "gamma", "d"),
        (22, "theta", "d"),
        (23, "vega", "d"),
        (24, "rho", "d"),
    ),
    "md.index_quote": ((7, "underlying", "s"), (8, "spot", "d")),
}


def encode_protobuf_one_field(event: Event) -> dict[str, bytes]:
    body = _pb_envelope(event)
    for number, name, kind in _PB_PAYLOAD[event.type]:
        value = getattr(event, name)
        if kind == "d":
            body += _pb_double(number, value)
        elif kind == "i":
            body += _pb_int(number, value)
        elif kind == "s":
            body += _pb_string(number, value)
        else:
            body += _pb_int(number, _micros(value))
    return {"type": event.type.encode(), "payload": body}


def _verify_protobuf_encoder() -> str:
    """Check the hand-written encoder against the real runtime, or say why not."""
    try:
        from google.protobuf import proto_builder
        from google.protobuf.descriptor_pb2 import FieldDescriptorProto as F
    except Exception as error:  # pragma: no cover - reported, not raised
        return f"NOT VERIFIED ({type(error).__name__}: no google.protobuf runtime)"
    cls = proto_builder.MakeSimpleProtoClass(
        OrderedDict([("a", F.TYPE_STRING), ("b", F.TYPE_INT64), ("c", F.TYPE_DOUBLE)]),
        full_name="r1.Check",
    )
    message = cls(a="DELTA-BTC-20260904-75600-P", b=1788431315798142, c=44.0)
    official = message.SerializeToString()
    ours = (
        _pb_string(1, "DELTA-BTC-20260904-75600-P")
        + _pb_int(2, 1788431315798142)
        + _pb_double(3, 44.0)
    )
    if ours == official:
        return "verified byte-for-byte against google.protobuf"
    return f"MISMATCH: ours {ours!r} vs runtime {official!r}"


ENCODINGS = OrderedDict(
    [
        ("A json:one-field", encode_json_one_field),
        ("B json:envelope-flat", encode_json_envelope_flat),
        ("C msgpack:envelope-flat", encode_msgpack_envelope_flat),
        ("D msgpack:one-field", encode_msgpack_one_field),
        ("E protobuf:one-field", encode_protobuf_one_field),
    ]
)


def entry_bytes(fields: dict[str, bytes]) -> int:
    """Field names plus values. What the entry is, before Redis's own per-entry cost."""
    return sum(len(name.encode()) + len(value) for name, value in fields.items())


def payload_bytes(fields: dict[str, bytes]) -> int:
    return len(fields.get("payload", b""))


# ------------------------------------------------------------------ redis truth


def redis_connection():
    try:
        import redis

        conn = redis.Redis.from_url(REDIS_URL, socket_connect_timeout=2)
        conn.ping()
        return conn
    except Exception:
        return None


def redis_bytes_per_entry(conn, events: list[Event], encode, repeats: int) -> float:
    key = "r1:measure:size"
    conn.delete(key)
    pipe = conn.pipeline(transaction=False)
    count = 0
    for _ in range(repeats):
        for event in events:
            pipe.xadd(key, encode(event))
            count += 1
            if count % 1000 == 0:
                pipe.execute()
                pipe = conn.pipeline(transaction=False)
    pipe.execute()
    used = conn.memory_usage(key)
    conn.delete(key)
    return used / count


def _fill(conn, key: str, entries) -> None:
    pipe = conn.pipeline(transaction=False)
    for n, fields in enumerate(entries, 1):
        pipe.xadd(key, fields)
        if n % 1000 == 0:
            pipe.execute()
            pipe = conn.pipeline(transaction=False)
    pipe.execute()


def _drop(conn, keys) -> None:
    pipe = conn.pipeline(transaction=False)
    for key in keys:
        pipe.delete(key)
    pipe.execute()


def per_stream_overhead(conn, events: list[Event], encode, streams: int, depth: int):
    """The same entries in one stream, and split across `streams` of them.

    `depth` entries each, because a stream holding a single entry is dominated by the
    listpack pre-allocation (`STREAM_LISTPACK_MAX_PRE_ALLOCATE`) that a filling node
    later shrinks away, and would overstate the steady-state cost of a key.
    """
    sample = events[:streams]
    total = len(sample) * depth

    _drop(conn, ["r1:measure:one"])
    _fill(
        conn,
        "r1:measure:one",
        (encode(sample[i % len(sample)]) for i in range(total)),
    )
    one = conn.memory_usage("r1:measure:one")
    _drop(conn, ["r1:measure:one"])

    keys = [f"r1:measure:many:{i}" for i in range(len(sample))]
    _drop(conn, keys)
    for key, event in zip(keys, sample, strict=True):
        _fill(conn, key, (encode(event) for _ in range(depth)))
    many = sum(conn.memory_usage(key) for key in keys)
    _drop(conn, keys)
    return total, one, many


def mixed_vs_homogeneous(conn, events: dict[str, list[Event]], encode, depth: int):
    """One stream per event type against one stream carrying all three, interleaved.

    Redis compresses a stream entry whose field names match the listpack node's *master
    entry* — `redis/redis`, `src/t_stream.c`, `STREAM_ITEM_FLAG_SAMEFIELDS`. A stream
    holding one event type has one field set and hits that path on nearly every entry;
    a stream carrying three does not. This measures the difference.
    """
    groups = list(events.values())
    per_type_keys = [f"r1:measure:split:{i}" for i in range(len(groups))]
    _drop(conn, per_type_keys + ["r1:measure:mixed"])

    for key, group in zip(per_type_keys, groups, strict=True):
        _fill(conn, key, (encode(group[i % len(group)]) for i in range(depth)))
    split = sum(conn.memory_usage(key) for key in per_type_keys)

    def interleaved():
        for i in range(depth):
            for group in groups:
                yield encode(group[i % len(group)])

    _fill(conn, "r1:measure:mixed", interleaved())
    mixed = conn.memory_usage("r1:measure:mixed")
    _drop(conn, per_type_keys + ["r1:measure:mixed"])
    return depth * len(groups), split, mixed


# ------------------------------------------------------------------ main


def main() -> None:
    events = real_events()
    conn = redis_connection()

    print("=" * 84)
    print("R1  PAYLOAD SIZE ON REDIS STREAMS")
    print("=" * 84)
    print(f"fixtures      : {FIXTURES}")
    for name, group in events.items():
        print(f"  {name:<22} {len(group):>4} real events via adapters.DeltaAdapter")
    print(f"protobuf      : {_verify_protobuf_encoder()}")
    print(
        "redis         : "
        + ("up at " + REDIS_URL if conn else "ABSENT - Redis columns skipped")
    )

    named = {name: group[0] for name, group in events.items()}
    print("\n" + "-" * 84)
    print("1. ONE NAMED EVENT, BYTES  (payload field / whole XADD entry incl. names)")
    print("-" * 84)
    for name, event in named.items():
        which = event.instrument.venue_symbol if event.instrument else event.underlying
        print(f"\n{name}   {which}")
        print(
            f"    {'encoding':<26}{'payload':>10}{'entry':>10}"
            f"{'fields':>9}{'vs JSON-1':>11}"
        )
        base = entry_bytes(encode_json_one_field(event))
        for label, encode in ENCODINGS.items():
            fields = encode(event)
            total = entry_bytes(fields)
            print(
                f"    {label:<26}{payload_bytes(fields):>10}{total:>10}{len(fields):>9}"
                f"{total / base:>10.2f}x"
            )

    print("\n" + "-" * 84)
    print("2. MEAN OVER EVERY FIXTURE EVENT, AND WHAT REDIS ACTUALLY HOLDS")
    print("-" * 84)
    redis_cost: dict[tuple[str, str], float] = {}
    for name, group in events.items():
        print(f"\n{name}   n={len(group)}")
        print(
            f"    {'encoding':<26}{'mean entry':>12}{'redis/entry':>14}{'overhead':>11}"
        )
        for label, encode in ENCODINGS.items():
            mean = sum(entry_bytes(encode(e)) for e in group) / len(group)
            if conn is None:
                print(f"    {label:<26}{mean:>11.1f}B{'-':>14}{'-':>11}")
                continue
            actual = redis_bytes_per_entry(conn, group, encode, repeats=40)
            redis_cost[(name, label)] = actual
            print(f"    {label:<26}{mean:>11.1f}B{actual:>13.1f}B{actual - mean:>10.1f}B")

    print("\n" + "-" * 84)
    print("3. MEMORY AT THIRTY MINUTES' RETENTION")
    print("-" * 84)
    book = (
        FRAMES_PER_SECOND
        * (1 / BOOK_INTERVAL_S)
        / (1 / BOOK_INTERVAL_S + 1 / TICKER_INTERVAL_S)
    )
    ticker = FRAMES_PER_SECOND - book
    rates = {
        "md.option_quote": book,
        "md.option_reference": ticker,
        "md.index_quote": ticker,
    }
    print(
        f"  frames/s        {FRAMES_PER_SECOND:>10.1f}   measured, "
        "tools/measure_feed.py, 2026-09-08"
    )
    print(
        f"  book frames/s   {book:>10.1f}   derived, "
        "split by the 508 ms / 5,001 ms intervals"
    )
    print(f"  ticker frames/s {ticker:>10.1f}   derived, same split")
    print(
        f"  events/s        {sum(rates.values()):>10.1f}   derived, "
        "one ticker frame is two events"
    )
    print(f"  retention       {RETENTION_SECONDS:>10} s\n")
    source = "measured on Redis" if conn else "derived from entry bytes only (no Redis)"
    print(f"    {'encoding':<26}{'bytes/s':>12}{'30 min':>12}    ({source})")
    for label, encode in ENCODINGS.items():
        per_second = 0.0
        for name, group in events.items():
            size = redis_cost.get((name, label))
            if size is None:
                size = sum(entry_bytes(encode(e)) for e in group) / len(group)
            per_second += rates[name] * size
        total = per_second * RETENTION_SECONDS
        print(f"    {label:<26}{per_second / 1024:>10.1f}K{total / 1024 / 1024:>10.1f}M")

    if conn is not None:
        print("\n" + "-" * 84)
        print("4. WHAT SPLITTING PER CONTRACT COSTS  (encoding B, 100 entries/stream)")
        print("-" * 84)
        group = events["md.option_quote"]
        n = len(group)
        total, one, many = per_stream_overhead(
            conn, group, encode_json_envelope_flat, n, depth=100
        )
        print(f"  {total:,} entries in 1 stream    : {one:>12,} bytes")
        print(f"  {total:,} entries in {n} streams : {many:>12,} bytes")
        print(
            f"  cost of the split           : {many - one:>12,} bytes "
            f"({(many - one) / n:,.0f} B per extra stream key, {many / one:.2f}x)"
        )

        print("\n" + "-" * 84)
        print("5. WHY ONE STREAM PER EVENT TYPE IS CHEAPER THAN ONE MIXED STREAM")
        print("-" * 84)
        total, split, mixed = mixed_vs_homogeneous(
            conn, events, encode_json_envelope_flat, depth=4000
        )
        print(f"  {total:,} entries, 3 streams one per type : {split:>12,} bytes")
        print(f"  {total:,} entries, 1 stream interleaved   : {mixed:>12,} bytes")
        print(
            f"  the mixed stream costs        : {mixed - split:>12,} bytes more "
            f"({mixed / split:.2f}x), {(mixed - split) / total:.1f} B per entry"
        )
        conn.close()


if __name__ == "__main__":
    main()
